#!/bin/bash
#
# The *linux-helper-install-scripts package* by **peter1000** <https://github.com/peter1000> is licensed under the GPLv2 License
# and adapted from [arch-install-scripts dated 2015-07-04](https://projects.archlinux.org/arch-install-scripts.git) - GPLv2 License
#
#   This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public 
#   License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any 
#   later version.
# 
#   This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied 
#   warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
#

. "${1:-./common}"
. ./test/common

ASSERT_streq ' deleted' "$(unmangle "$(mangle ' deleted')")"
ASSERT_streq '\040deleted' "$(mangle "$(unmangle '\040deleted')")"
ASSERT_streq 'foo\011\040\011bar' "$(mangle $'foo\t \tbar')"
